ess-controller_variant: "test_type_1"
twins_variant: "test_type_1"

site-controller_templates:
  - path: sc_template.json
    filename_pattern:
      type: sequential
      filename_template: sc-{{target}}.json
      from: 1
      to: 15
    content_replacements:
      - target: "{{SC_ID}}"
      - target: "{{SC_IP_SEGMENT}}"
        list:
          - "0"
          - "2"
          - "4"
          - "6"
          - "8"
          - "0"
          - "2"
          - "4"
          - "6"
          - "8"
          - "0"
          - "2"
          - "4"
          - "6"
          - "8"
      - target: "{{FIRST_COMPONENT}}"
        list:
          - "controller_01"
      - target: "{{SECOND_COMPONENT}}"

ess-controller_templates:
  - path: ess_template.json
    filename_pattern:
      type: list
      filename_template: ess-{{target}}-file.json
      list: 
        - "alpha"
        - "beta"
        - "delta" 

  - path: ess_base_file.json
    filename_pattern:
      type: sequential
      filename_template: ess-{{target}}-file.json
      from: 0
      to: 2 
    content_replacements:
      - target: "{{connection}}"
        list:
          - "twins-01"
          - "twins-01"
          - "twins-01"
      - target: "\"{{VIRTUAL_PORT}}\""
        list:
          - "10001"
          - "10002"
          - "10003"
      - target: "{{Virtual_ID}}"

replacements:
  - target: "{{SITE_ID}}"
    value:  test_site
  - target: "{{EMC_ID}}"
    value:  test_emc
  - target: "{{EMC_NAME}}"
    value:  TEST EMC
  - target: "{{SITE_NAME}}"
    value:  TEST SITE
  - target: "{{SPECIAL_IP}}"
    value: "1.1.1.1"
    exclude: "ess-controller/*"
  - target: "{{SPECIAL_IP}}"
    value: "0.0.0.0"
    include: "ess-controller/*"
  - target: "{{LOWER_MAX}}"
    value: "-2500"
  - target: "{{HIGHER_MAX}}"
    value: "-2300"